# Generated by Django 4.0.10 on 2026-02-15 13:29

import bson.objectid
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField()),
                ('client_id', models.CharField(db_index=True, max_length=255)),
                ('slug', models.CharField(db_index=True, max_length=255)),
                ('deleted_status', models.CharField(max_length=1)),
                ('status', models.CharField(db_index=True, max_length=50)),
                ('audit_data', djongo.models.fields.JSONField()),
                ('metadata', djongo.models.fields.JSONField()),
            ],
        ),
        migrations.AddIndex(
            model_name='bot',
            index=models.Index(fields=['client_id'], name='bots_bot_client__5091ff_idx'),
        ),
        migrations.AddIndex(
            model_name='bot',
            index=models.Index(fields=['slug'], name='bots_bot_slug_133b4f_idx'),
        ),
        migrations.AddIndex(
            model_name='bot',
            index=models.Index(fields=['status'], name='bots_bot_status_7ce791_idx'),
        ),
    ]
