# Generated by Django 5.2.11 on 2026-02-11 12:24

import django_mongodb_backend.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample_mflix', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='id',
            field=django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
